---
# handlers file for $roletemplate

# - name: restart $service
#   sudo: yes
#   service: name=$service state=restarted

# - name: reload $service
#   sudo: yes
#   service: name=$service state=reloaded
